name: Test & Lint

# Run the tests on any branch push
on:
  push:
    branches:
     - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Format
        run: make fmt

      - name: Vet
        run: make vet

      - name: Generate Go Code
        run: make generate

      - name: Generate Manifests
        run: make manifests

      - name: Verify No Changes
        id: verify-no-changes
        uses: tj-actions/verify-changed-files@v8.8

      - name: Fail If Changes
        if: steps.verify-no-changes.outputs.files_changed == 'true'
        run: "false"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes: [1.21, 1.22, 1.23]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        env:
          ENVTEST_K8S_VERSION: ${{ matrix.kubernetes }}
        run: make test
